export const RESET_PASSWORD = 'RESET_PASSWORD';

export const LAST_SEEN_NOTIFS_TIME = 'SEEN_NOTIFS';

export const GOOGLE_LOGIN_ID = 'GOOGLE_LOGIN_ID';

export const APPLE_LOGIN_ID = 'APPLE_LOGIN_ID';
