import '@capacitor/app/dist/esm/web.js';
import '@capacitor/screen-orientation/dist/esm/web.js';
import '@capacitor/splash-screen/dist/esm/web.js';
import 'stores/entities/useEntity';
import 'stores/entities/useAllEntities';
import 'stores/entities/useEntitiesArr';
import 'stores/entities/useEntitiesMap';
import 'stores/entities/useEntitiesByFields';
import 'stores/entities/useRelation';
