--
-- PostgreSQL database dump
--


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __migration__; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.__migration__ (
    "lastMigration" text NOT NULL,
    rollback json NOT NULL
);


--
-- Name: __test__; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.__test__ (
    id bigint NOT NULL,
    unindexed bigint NOT NULL,
    name character varying NOT NULL
);

ALTER TABLE ONLY public.__test__ REPLICA IDENTITY FULL;


--
-- Name: chat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat (
    id bigint NOT NULL,
    "ownerId" bigint NOT NULL
);


--
-- Name: chatParticipant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."chatParticipant" (
    id bigint NOT NULL,
    "chatId" bigint NOT NULL,
    "userId" bigint NOT NULL,
    "lastReadTime" timestamp(6) with time zone DEFAULT '1970-01-01 00:00:01-08'::timestamp with time zone NOT NULL
);


--
-- Name: chatParticipant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."chatParticipant" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."chatParticipant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: chatReply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."chatReply" (
    id bigint NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "parentEntityId" bigint NOT NULL,
    "parentReplyId" bigint,
    "authorId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    content text NOT NULL
);


--
-- Name: chatReply_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."chatReply" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."chatReply_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: city; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.city (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    "nameAscii" character varying(50) NOT NULL,
    "countryCode" character(2) NOT NULL,
    lat real NOT NULL,
    lng real NOT NULL
);


--
-- Name: city_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.city ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: club; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.club (
    id bigint NOT NULL,
    "parentClubId" bigint,
    name character varying(30) NOT NULL,
    description text,
    "isAdult" boolean NOT NULL,
    "finalPicUrl" text
);


--
-- Name: club_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.club ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.club_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: follow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.follow (
    id bigint NOT NULL,
    "followeeId" bigint NOT NULL,
    "followerId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);


--
-- Name: follow_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.follow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: mzTest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."mzTest" (
    id bigint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


--
-- Name: notif; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notif (
    id bigint NOT NULL,
    "notifType" character varying(30) NOT NULL,
    "userId" bigint NOT NULL,
    "groupingId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    params text NOT NULL,
    "hasRead" boolean DEFAULT false NOT NULL
);


--
-- Name: notif_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notif ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notif_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post (
    id bigint NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "authorId" bigint NOT NULL,
    "clubId" bigint NOT NULL,
    "cityId" bigint,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    "mediaUrl" character varying(255),
    "mediaRatio" real,
    "thumbUrl" character varying(255),
    content text
);


--
-- Name: postMeta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."postMeta" (
    id bigint NOT NULL,
    "postId" bigint NOT NULL,
    "metaKey" character varying(30) NOT NULL,
    "metaValue" text NOT NULL
);


--
-- Name: postMeta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."postMeta" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."postMeta_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: postReply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."postReply" (
    id bigint NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "parentEntityId" bigint NOT NULL,
    "parentReplyId" bigint,
    "authorId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    content text NOT NULL
);


--
-- Name: postReply_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."postReply" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."postReply_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: reaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reaction (
    id bigint NOT NULL,
    "userId" bigint NOT NULL,
    "entityType" character varying(30) NOT NULL,
    "entityId" bigint NOT NULL,
    "reactType" character varying(2) NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);


--
-- Name: reaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report (
    id bigint NOT NULL,
    "reporterId" bigint NOT NULL,
    "entityType" character varying(30) NOT NULL,
    "entityId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);


--
-- Name: report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    "clubId" bigint NOT NULL,
    "cityId" bigint
);


--
-- Name: roomReply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."roomReply" (
    id bigint NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "parentEntityId" bigint NOT NULL,
    "parentReplyId" bigint,
    "authorId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    content text NOT NULL
);


--
-- Name: roomReply_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."roomReply" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."roomReply_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: test_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.__test__ ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password text NOT NULL,
    name character varying(50) NOT NULL,
    birthday date NOT NULL,
    "registerTime" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    "cityId" bigint,
    "photoUrl" character varying(255),
    "thumbUrl" character varying(255),
    "coverPhotoUrls" text,
    school character varying(50),
    "jobTitle" character varying(50),
    "jobCompany" character varying(50),
    bio text
);


--
-- Name: userBlock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."userBlock" (
    id bigint NOT NULL,
    "blockerId" bigint NOT NULL,
    "blockeeId" bigint NOT NULL,
    "time" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);


--
-- Name: userBlock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."userBlock" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."userBlock_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: userClub; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."userClub" (
    id bigint NOT NULL,
    "userId" bigint NOT NULL,
    "clubId" bigint NOT NULL,
    "joinTime" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    privacy character varying(30) DEFAULT 'public'::character varying NOT NULL,
    "order" smallint DEFAULT '0'::smallint NOT NULL
);


--
-- Name: userClubMeta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."userClubMeta" (
    id bigint NOT NULL,
    "userClubId" bigint NOT NULL,
    "metaKey" character varying(30) NOT NULL,
    "metaValue" text NOT NULL
);


--
-- Name: userClubMeta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."userClubMeta" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."userClubMeta_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: userClub_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."userClub" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."userClub_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: userMeta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."userMeta" (
    id bigint NOT NULL,
    "userId" bigint NOT NULL,
    "metaKey" character varying(30) NOT NULL,
    "metaValue" text NOT NULL
);


--
-- Name: userMeta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."userMeta" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."userMeta_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: __test__ __test___pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.__test__ ADD CONSTRAINT __test___pkey PRIMARY KEY (id);


--
-- Name: chatParticipant chatParticipant_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatParticipant" ADD CONSTRAINT "chatParticipant_id_idx" PRIMARY KEY (id);


--
-- Name: chatReply chatReply_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatReply" ADD CONSTRAINT "chatReply_id_idx" PRIMARY KEY (id);


--
-- Name: chat chat_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat ADD CONSTRAINT chat_id_idx PRIMARY KEY (id);


--
-- Name: city city_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.city ADD CONSTRAINT city_id_idx PRIMARY KEY (id);


--
-- Name: club club_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club ADD CONSTRAINT club_id_idx PRIMARY KEY (id);


--
-- Name: follow follow_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow ADD CONSTRAINT follow_id_idx PRIMARY KEY (id);


--
-- Name: mzTest mzTest_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."mzTest" ADD CONSTRAINT "mzTest_id_idx" PRIMARY KEY (id);


--
-- Name: notif notif_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notif ADD CONSTRAINT notif_id_idx PRIMARY KEY (id);


--
-- Name: postMeta postMeta_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."postMeta" ADD CONSTRAINT "postMeta_id_idx" PRIMARY KEY (id);


--
-- Name: postReply postReply_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."postReply" ADD CONSTRAINT "postReply_id_idx" PRIMARY KEY (id);


--
-- Name: post post_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post ADD CONSTRAINT post_id_idx PRIMARY KEY (id);


--
-- Name: reaction reaction_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reaction ADD CONSTRAINT reaction_id_idx PRIMARY KEY (id);


--
-- Name: report report_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report ADD CONSTRAINT report_id_idx PRIMARY KEY (id);


--
-- Name: roomReply roomReply_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roomReply" ADD CONSTRAINT "roomReply_id_idx" PRIMARY KEY (id);


--
-- Name: room room_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room ADD CONSTRAINT room_id_idx PRIMARY KEY (id);


--
-- Name: userBlock userBlock_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userBlock" ADD CONSTRAINT "userBlock_id_idx" PRIMARY KEY (id);


--
-- Name: userClubMeta userClubMeta_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userClubMeta" ADD CONSTRAINT "userClubMeta_id_idx" PRIMARY KEY (id);


--
-- Name: userClub userClub_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userClub" ADD CONSTRAINT "userClub_id_idx" PRIMARY KEY (id);


--
-- Name: userMeta userMeta_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userMeta" ADD CONSTRAINT "userMeta_id_idx" PRIMARY KEY (id);


--
-- Name: user user_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user" ADD CONSTRAINT user_id_idx PRIMARY KEY (id);


--
-- Name: chatParticipant_chatId_userId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "chatParticipant_chatId_userId_idx" ON public."chatParticipant" USING btree ("chatId" DESC NULLS LAST, "userId" DESC NULLS LAST);


--
-- Name: chatParticipant_userId_chatId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "chatParticipant_userId_chatId_idx" ON public."chatParticipant" USING btree ("userId" DESC NULLS LAST, "chatId" DESC NULLS LAST);


--
-- Name: city_lat_lng_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX city_lat_lng_idx ON public.city USING btree (lat DESC NULLS LAST, lng DESC NULLS LAST);


--
-- Name: city_name_countryCode_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "city_name_countryCode_idx" ON public.city USING btree (name, "countryCode");


--
-- Name: club_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX club_name_idx ON public.club USING btree (name);


--
-- Name: follow_followeeId_followerId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "follow_followeeId_followerId_idx" ON public.follow USING btree ("followeeId" DESC NULLS LAST, "followerId" DESC NULLS LAST);


--
-- Name: follow_followerId_followeeId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "follow_followerId_followeeId_idx" ON public.follow USING btree ("followerId" DESC NULLS LAST, "followeeId" DESC NULLS LAST);


--
-- Name: notif_notifType_userId_groupingId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "notif_notifType_userId_groupingId_idx" ON public.notif USING btree ("notifType", "userId" DESC NULLS LAST, "groupingId" DESC NULLS LAST);


--
-- Name: postMeta_postId_metaKey_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "postMeta_postId_metaKey_idx" ON public."postMeta" USING btree ("postId" DESC NULLS LAST, "metaKey");


--
-- Name: reaction_entityType_entityId_userId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "reaction_entityType_entityId_userId_idx" ON public.reaction USING btree ("entityType", "entityId" DESC NULLS LAST, "userId" DESC NULLS LAST);


--
-- Name: report_reporterId_entityType_entityId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "report_reporterId_entityType_entityId_idx" ON public.report USING btree ("reporterId" DESC NULLS LAST, "entityType", "entityId" DESC NULLS LAST);


--
-- Name: room_cityId_clubId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "room_cityId_clubId_idx" ON public.room USING btree ("cityId" DESC NULLS LAST, "clubId" DESC NULLS LAST) NULLS NOT DISTINCT;


--
-- Name: room_clubId_cityId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "room_clubId_cityId_idx" ON public.room USING btree ("clubId" DESC NULLS LAST, "cityId" DESC NULLS LAST) NULLS NOT DISTINCT;


--
-- Name: userBlock_blockeeId_blockerId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "userBlock_blockeeId_blockerId_idx" ON public."userBlock" USING btree ("blockeeId" DESC NULLS LAST, "blockerId" DESC NULLS LAST);


--
-- Name: userBlock_blockerId_blockeeId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "userBlock_blockerId_blockeeId_idx" ON public."userBlock" USING btree ("blockerId" DESC NULLS LAST, "blockeeId" DESC NULLS LAST);


--
-- Name: userClubMeta_userClubId_metaKey_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "userClubMeta_userClubId_metaKey_idx" ON public."userClubMeta" USING btree ("userClubId" DESC NULLS LAST, "metaKey");


--
-- Name: userClub_clubId_userId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "userClub_clubId_userId_idx" ON public."userClub" USING btree ("clubId" DESC NULLS LAST, "userId" DESC NULLS LAST);


--
-- Name: userClub_userId_clubId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "userClub_userId_clubId_idx" ON public."userClub" USING btree ("userId" DESC NULLS LAST, "clubId" DESC NULLS LAST);


--
-- Name: userMeta_userId_metaKey_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "userMeta_userId_metaKey_idx" ON public."userMeta" USING btree ("userId" DESC NULLS LAST, "metaKey");


--
-- Name: user_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_email_idx ON public."user" USING btree (email);


--
-- Name: chatParticipant chatParticipant_chatId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatParticipant" ADD CONSTRAINT "chatParticipant_chatId_fk" FOREIGN KEY ("chatId") REFERENCES public.chat(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: chatParticipant chatParticipant_userId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatParticipant" ADD CONSTRAINT "chatParticipant_userId_fk" FOREIGN KEY ("userId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: chatReply chatReply_authorId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatReply" ADD CONSTRAINT "chatReply_authorId_fk" FOREIGN KEY ("authorId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: chatReply chatReply_chatId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatReply" ADD CONSTRAINT "chatReply_chatId_fk" FOREIGN KEY ("parentEntityId") REFERENCES public.chat(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: chatReply chatReply_parentReplyId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."chatReply" ADD CONSTRAINT "chatReply_parentReplyId_fk" FOREIGN KEY ("parentReplyId") REFERENCES public."chatReply"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: chat chat_ownerId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat ADD CONSTRAINT "chat_ownerId_fk" FOREIGN KEY ("ownerId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: club club_parentClubId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club ADD CONSTRAINT "club_parentClubId_fk" FOREIGN KEY ("parentClubId") REFERENCES public.club(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: follow follow_followeeId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow ADD CONSTRAINT "follow_followeeId_fk" FOREIGN KEY ("followeeId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: follow follow_followerId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow ADD CONSTRAINT "follow_followerId_fk" FOREIGN KEY ("followerId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: notif notif_userId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notif ADD CONSTRAINT "notif_userId_fk" FOREIGN KEY ("userId") REFERENCES public."user"(id);


--
-- Name: postMeta postMeta_postId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."postMeta" ADD CONSTRAINT "postMeta_postId_fk" FOREIGN KEY ("postId") REFERENCES public.post(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: postReply postReply_authorId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."postReply" ADD CONSTRAINT "postReply_authorId_fk" FOREIGN KEY ("authorId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: postReply postReply_parentReplyId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."postReply" ADD CONSTRAINT "postReply_parentReplyId_fk" FOREIGN KEY ("parentReplyId") REFERENCES public."postReply"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: postReply postReply_postId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."postReply" ADD CONSTRAINT "postReply_postId_fk" FOREIGN KEY ("parentEntityId") REFERENCES public.post(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: post post_authorId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post ADD CONSTRAINT "post_authorId_fk" FOREIGN KEY ("authorId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: post post_cityId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post ADD CONSTRAINT "post_cityId_fk" FOREIGN KEY ("cityId") REFERENCES public.city(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: post post_clubId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post ADD CONSTRAINT "post_clubId_fk" FOREIGN KEY ("clubId") REFERENCES public.club(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: report report_reporterId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report ADD CONSTRAINT "report_reporterId_fk" FOREIGN KEY ("reporterId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: roomReply roomReply_authorId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roomReply" ADD CONSTRAINT "roomReply_authorId_fk" FOREIGN KEY ("authorId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: roomReply roomReply_parentReplyId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roomReply" ADD CONSTRAINT "roomReply_parentReplyId_fk" FOREIGN KEY ("parentReplyId") REFERENCES public."roomReply"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: roomReply roomReply_roomId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."roomReply" ADD CONSTRAINT "roomReply_roomId_fk" FOREIGN KEY ("parentEntityId") REFERENCES public.room(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: room room_cityId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room ADD CONSTRAINT "room_cityId_fk" FOREIGN KEY ("cityId") REFERENCES public.city(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: room room_clubId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room ADD CONSTRAINT "room_clubId_fk" FOREIGN KEY ("clubId") REFERENCES public.club(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: userBlock userBlock_blockeeId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userBlock" ADD CONSTRAINT "userBlock_blockeeId_fk" FOREIGN KEY ("blockeeId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: userBlock userBlock_blockerId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userBlock" ADD CONSTRAINT "userBlock_blockerId_fk" FOREIGN KEY ("blockerId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: userClubMeta userClubMeta_userClubId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userClubMeta" ADD CONSTRAINT "userClubMeta_userClubId_fk" FOREIGN KEY ("userClubId") REFERENCES public."userClub"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: userClub userClub_clubId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userClub" ADD CONSTRAINT "userClub_clubId_fk" FOREIGN KEY ("clubId") REFERENCES public.club(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: userClub userClub_userId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userClub" ADD CONSTRAINT "userClub_userId_fk" FOREIGN KEY ("userId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: userMeta userMeta_userId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userMeta" ADD CONSTRAINT "userMeta_userId_fk" FOREIGN KEY ("userId") REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: user user_cityId_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user" ADD CONSTRAINT "user_cityId_fk" FOREIGN KEY ("cityId") REFERENCES public.city(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

