--
-- PostgreSQL database dump
--


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __migration__; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.__migration__ (
    "lastMigration" text NOT NULL,
    rollback json NOT NULL
);


--
-- Name: __test__; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.__test__ (
    id bigint NOT NULL,
    unindexed bigint NOT NULL,
    name character varying NOT NULL
);

ALTER TABLE ONLY public.__test__ REPLICA IDENTITY FULL;


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password text NOT NULL,
    name character varying(50) NOT NULL,
    birthday date NOT NULL,
    "registerTime" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    "cityId" bigint,
    "photoUrl" character varying(255),
    "thumbUrl" character varying(255),
    "coverPhotoUrls" text,
    school character varying(50),
    "jobTitle" character varying(50),
    "jobCompany" character varying(50),
    bio text
);


--
-- Name: test_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.__test__ ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1 );


--
-- Name: __test__ __test___pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.__test__ ADD CONSTRAINT __test___pkey PRIMARY KEY (id);


--
-- Name: user user_id_idx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user" ADD CONSTRAINT user_id_idx PRIMARY KEY (id);


--
-- Name: user_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_email_idx ON public."user" USING btree (email);
